import java.io.File;
import java.io.FileNotFoundException;
import java.util.*;

public class eng_p1 {
    public static void main(String[] args) throws FileNotFoundException {
        //to store start stage
        int start = 0;
        String prospect = "";
        Stack<String> currstack = new Stack<>();

        //for list of transitions
        //look up transitions.get(curr state) to reduce runtime
        HashMap <Integer,ArrayList <transition>> transitions = new HashMap<>();

        //ensure each config is processed once
        //preventing infinity loops
        HashSet <configuration> visited = new HashSet<>();

        //keep track of configs generated by simulation
        ArrayList<configuration> queue = new ArrayList<>();

        //set of accepting states
        //if not in this set, reject
        HashSet <Integer> acceptstates = new HashSet<>();

        //keep track of generated configurations by simulate
        //ArrayList <transition> info = new ArrayList<>();

        //integer arrays to store what stages we accept/reject at
        HashSet <Integer> accept = new HashSet<>();
        HashSet <Integer> reject = new HashSet<>();        

        //1. put all user input into Arraylist transitions
        Scanner scanner = new Scanner(new File(args[0]));
        prospect = args[1];
        //System.out.println("String: " + prospect);
        //int counter = 1;
        
        while (scanner.hasNextLine()) {
            

            String line = scanner.nextLine();
            String[] input = line.split("\\s+");

            if (input[0].equals("state")) {

                int id = Integer.parseInt(input[1]);

                if (input.length > 2) {
                    if (input[2].equals("start")) {
                        start = Integer.parseInt(input[1]);
                        
                    }
                    if (input[2].equals("accept")) {
                        acceptstates.add(Integer.parseInt(input[1]));
                    }
                }

                //input.add(new State(id, isStart, isAccept));
            }

            else if (input[0].equals("transition")) {

                //debug purposes 
                /*
                System.out.println("Transition " + counter );
                counter++;
                */

                int from = Integer.parseInt(input[1]);
                String read = input[2];
                String pop = input[3];
                int to = Integer.parseInt(input[4]);
                String push = input[5];

                transition t = new transition(from, read, pop, to, push);

                //creates an empty arraylist for the state
                if (!transitions.containsKey(from)) {
                    transitions.put(from, new ArrayList<>());
                }

                // Add transition to the state list
                transitions.get(from).add(t);
            }
        }

        scanner.close();

        // Test to make sure program is storing data properly
        /* 
        System.out.println("Accept States");
        for (int i : acceptstates) {
            System.out.println(i + " ");
        }

        System.out.println("\n Transition States");
        for (Map.Entry<Integer, ArrayList<transition>> entry : transitions.entrySet()) {

        int state = entry.getKey();
        ArrayList<transition> list = entry.getValue();

        System.out.println("From state: " + state);

            for (transition t : list) {
                System.out.println("   " + t);
            }
        }
        */

        //2.iterate through arraylist of queue
        //stop when theres no more elements to visit
        String remaining = "";
        
        //based on start node, add subsequent transitions to queue
        for (transition t : transitions.get(start)) {
            Stack<String> stackcpy = new Stack<>();
            stackcpy = currstack;

            /*
            //what are you popping?
            if((t.popSymbol).equals("$")){
                currstack.pop();
            }
            else if((t.popSymbol).equals("1")){
                currstack.pop();
            }
            else if((t.popSymbol).equals("0")){
                currstack.pop();
            }
            //empty string case
            else{
                if(!currstack.isEmpty()){
                    currstack.pop();
                }
                //do nothing essentially
            }


            //what are you pushing?
            if((t.pushSymbol).equals("$")){
                currstack.push("$");
                currstack.push("E");
            }
            else if((t.pushSymbol).equals("1")){
                currstack.push("1");
            }
            else if((t.pushSymbol).equals("0")){
                currstack.push("0");
            }
            //empty string case
            else{
                currstack.push("E");
                //do nothing essentially
            }

            */
            configuration c = new configuration(t.fromState, prospect, currstack);
            queue.add(c);
            System.out.println("current stack at start " + c);
        }

        

        //look at  top config
        while(!queue.isEmpty()){
        //for (configuration con: queue){
            configuration con = queue.getFirst();

            System.out.println("Current top queue config:" + con);
            int fromState;
            String readSymbol; 
            String popSymbol;
            int toState;
            String pushSymbol;

            //if you've already done this config, skip it bc its a duplicate
            if (visited.contains(con)){
                System.out.println("Skipped" + con);
                queue.remove(0);

            }
            /* 
            //edge case, no where else to go,
            if(transitions.get(con.state).isEmpty()){
                visited.add(con);
            }
            
            */
            

            //edge case if its empty, we have finished our string
            if ((con.remainingInput).isEmpty() || con.remainingInput.equals("E")){

                //is this accept? if yes: add to accept hashset
                for (Integer i: acceptstates){
                    if (i.equals(con.state)){
                        System.out.println("Added" + i + "to accept state");
                        accept.add(i);
                    }
                }
                //else, reject
                reject.add(con.state);
                System.out.println("Added" + con.state + "to reject state");
            }
            
            //we visited it
            visited.add(con);
            queue.remove(0);
            
            //main case, we still have remaining string
             Stack<String> stackcpy = new Stack<>();
             
            
             //find the transition info
            for (transition t : transitions.get(con.state)) {
                //System.out.println("Finding transition info...");
                    stackcpy = con.stack;
                    fromState = t.fromState;
                    readSymbol = t.readSymbol;
                    popSymbol = t.popSymbol;
                    toState = t.toState;
                    pushSymbol = t.pushSymbol;
                    remaining = con.remainingInput;
                
                    //valid transition
                    //System.out.println((con.remainingInput).substring(0,1));
                    if((con.remainingInput).substring(0,1).equals(readSymbol) || readSymbol.equals("E")){
                    System.out.println("transition" + t + "is a valid transition");

                        String temp = "";

                        if(!stackcpy.isEmpty()){
                            temp = stackcpy.pop();
                        }

                        //pop symbol must be the same
                        if (temp.equals(popSymbol) || readSymbol.equals("E")){
                            stackcpy.push(pushSymbol);
                            
                            System.out.println("pop symbol" + popSymbol + "is a valid transition");


                            remaining = con.remainingInput.substring(1);
                            configuration c = new configuration(toState, remaining, stackcpy);
                            
                            queue.add(c);
                            //visited.add(con);

                        }
                        //invalid transition, do nothing

                    }
                    //not a valid transition, don't do anything
                    else{
                        System.out.println("Not a valid transition");
                    }

                    
                    
                }
             
             }
            
        //System.out.println("FINISHED FOR LOOP");

        //print results
        if(!accept.isEmpty()){
            for (Integer i : accept){
                System.out.println("accept ");
                System.out.println(i + " ");
            }
        }
        else{
            for (Integer i : reject){
                System.out.println("reject ");
                System.out.println(i + " ");
            }
        }
        
            
    
    }
}


