import java.io.File;
import java.io.FileNotFoundException;
import java.util.*;

public class eng_p1 {
    public static void main(String[] args) throws FileNotFoundException {
        //to store start stage
        int start = 0;
        String prospect = "";
        Stack<String> currstack = new Stack<>();

        //for list of transitions
        //look up transitions.get(curr state) to reduce runtime
        HashMap <Integer,ArrayList <transition>> transitions = new HashMap<>();

        //ensure each config is processed once
        //preventing infinity loops
        HashSet <configuration> visited = new HashSet<>();

        //keep track of configs generated by simulation
        ArrayList<configuration> queue = new ArrayList<>();

        //set of accepting states
        //if not in this set, reject
        HashSet <Integer> acceptstates = new HashSet<>();

        //keep track of generated configurations by simulate
        //ArrayList <transition> info = new ArrayList<>();

        //integer arrays to store what stages we accept/reject at
        HashSet <Integer> accept = new HashSet<>();
        HashSet <Integer> reject = new HashSet<>();        

        //1. put all user input into Arraylist transitions
        Scanner scanner = new Scanner(new File(args[0]));
        prospect = args[1];
        boolean allrejects = false;
        //System.out.println("String: " + prospect);
        //int counter = 1;
        
        while (scanner.hasNextLine()) {
            

            String line = scanner.nextLine();
            String[] input = line.split("\\s+");

            if (input[0].equals("state")) {

                int id = Integer.parseInt(input[1]);

                if (input.length > 2) {
                    if (input[2].equals("start")) {
                        start = Integer.parseInt(input[1]);
                        
                    }
                    if (input[2].equals("accept")) {
                        acceptstates.add(Integer.parseInt(input[1]));
                    }
                }

                //input.add(new State(id, isStart, isAccept));
            }

            else if (input[0].equals("transition")) {

                //debug purposes 
                /*
                System.out.println("Transition " + counter );
                counter++;
                */

                int from = Integer.parseInt(input[1]);
                String read = input[2];
                String pop = input[3];
                int to = Integer.parseInt(input[4]);
                String push = input[5];

                transition t = new transition(from, read, pop, to, push);

                //creates an empty arraylist for the state
                if (!transitions.containsKey(from)) {
                    transitions.put(from, new ArrayList<>());
                }

                // Add transition to the state list
                transitions.get(from).add(t);
            }
        }

        scanner.close();

        // Test to make sure program is storing data properly
        /* 
        System.out.println("Accept States");
        for (int i : acceptstates) {
            System.out.println(i + " ");
        }

        System.out.println("\n Transition States");
        for (Map.Entry<Integer, ArrayList<transition>> entry : transitions.entrySet()) {

        int state = entry.getKey();
        ArrayList<transition> list = entry.getValue();

        System.out.println("From state: " + state);

            for (transition t : list) {
                System.out.println("   " + t);
            }
        }
        */

        //2.iterate through arraylist of queue
        //stop when theres no more elements to visit
        String remaining = "";
        
        //based on start node, add subsequent transitions to queue
        for (transition t : transitions.get(start)) {
            Stack<String> stackcpy = new Stack<>();
            stackcpy = currstack;

            configuration c = new configuration(t.fromState, prospect, currstack);
            queue.add(c);
            //System.out.println("current stack at start " + c);
        }

        

        //look at  top config
        while(!queue.isEmpty()){
        //for (configuration con: queue){
            configuration con = queue.getFirst();
            boolean moretransitions = false;
            //con.foundTransition = false;

            //System.out.println("\nCurrent top queue config:" + con);
            Stack<String> stackcpy = (Stack<String>)con.stack.clone();
            int fromState;
            String readSymbol; 
            String popSymbol;
            int toState;
            String pushSymbol;
            

            //if you've already done this config, skip it bc its a duplicate
            if (visited.contains(con)){
                //System.out.println("Skipped" + con);
                queue.remove(con);
                continue;
            }

            //edge case if its empty, we have finished our string
            //stackcpy does not necessarily have to be empty
            if ((con.remainingInput).isEmpty() ){
                //is this accept? if yes: add to accept hashset
                //for (Integer i: acceptstates){
                    //if (i.equals(con.state)){

                    if(acceptstates.contains(con.state)){
                        //System.out.println("Added" + con.state + "to accept state");
                        accept.add(con.state);
                    }
                    else{
                        //else, reject
                        reject.add(con.state);
                        //System.out.println("Added" + con.state + "to reject state");

                    }
                //}
            
            }
            
            //we visited it
            visited.add(con);
            queue.remove(0);

            //main case, we still have remaining string
             
             
            if(transitions.containsKey(con.state)){
             //find the transition info
                for (transition t : transitions.get(con.state)) {
                //System.out.println("Finding transition info...");
                    stackcpy = (Stack<String>)con.stack.clone();
                    fromState = t.fromState;
                    readSymbol = t.readSymbol;
                    popSymbol = t.popSymbol;
                    toState = t.toState;
                    pushSymbol = t.pushSymbol;
                    remaining = con.remainingInput;
                    String compare = "";
                    
                    if (!remaining.isEmpty()){
                         compare = remaining.substring(0,1);
                    }
                
                    //valid transition
                    //System.out.println((con.remainingInput).substring(0,1));
                    if(!remaining.isEmpty() || remaining.isEmpty() && !stackcpy.isEmpty()){
                        //removed remaining.isempty from last statement to see if that makes a difference??
                        if((compare.equals(readSymbol) && !stackcpy.isEmpty() && (stackcpy.peek().equals(popSymbol)))
                        || (compare.equals(readSymbol) && popSymbol.equals("E"))
                        || (readSymbol.equals("E") && popSymbol.equals("E") )
                        || (readSymbol.equals("E") &&!stackcpy.isEmpty() && (stackcpy.peek().equals(popSymbol)))
                 
                    )
                        
                        {
                        //System.out.println("WE TAKE" + t + "as a valid transition string:" + remaining + "pop?" + popSymbol);
                        moretransitions = true;
                        //con.foundTransition = true;

                            //check if reading epsilon do smth
                            if (readSymbol.equals("E")){

                            }
                            else{
                                remaining = con.remainingInput.substring(1);
                            }

                            //popping epsilon do smth diff
                            if(popSymbol.equals("E")){

                            }
                            else{
                                if(!stackcpy.isEmpty()){
                                    stackcpy.pop();
                                }
                            }

                            //pushing epsilon do smth diff
                            if(pushSymbol.equals("E")){

                            }
                            else{
                                stackcpy.push(pushSymbol);
                            }

                        configuration c = new configuration(toState, remaining, stackcpy);
                        
                        if(!visited.contains(c)){
                            queue.add(c);
                            //System.out.println("ADD " + c + " TO QUEUE");
                        }
                        

                        }
                        //not a valid transition, don't do anything
                        else{

                            //System.out.println("WE DO NOT TAKE" + t + "string:" + remaining + "pop?" + popSymbol);
                            //System.out.println("String" + remaining + "Compare:" + compare + "vs. readsym: " + readSymbol);
                            
                             /* 
                            if (( !stackcpy.isEmpty() && (stackcpy.peek().equals(popSymbol)))){
                                System.out.println("1 pass");
                            }
                            else{
                                System.out.println("stack empty?" + stackcpy.isEmpty());
                                System.out.println("stack top?" + stackcpy.peek());
                                System.out.println("pop?"+ popSymbol);
                            }
                             
                            if (!( popSymbol.equals("E"))){
                                System.out.println("2 failed");

                            }
                            if (!(readSymbol.equals("E"))){
                                System.out.println("3 failed");
                            }
                            */
                                
                            
                        }
                    }
                    
                }
                     
            }
             
            //reject no more possible transitions
            if(!moretransitions && con.remainingInput.isEmpty()){
                //System.out.println("Config stuck, auto add to reject");
                reject.add(con.state);
            }
        }
            
            
       // System.out.println("FINISHED FOR LOOP");


       //edge case no more transitions to take buut string didn't finish
       /* 
       if(accept.isEmpty() && !remaining.isEmpty()){
        System.out.println("reject");
       }
       */
        //print results
        if(!accept.isEmpty()){
            System.out.print("accept ");
            for (Integer i : accept){
                System.out.print(i + " ");
                //System.out.print(i + " ");
            }
        }
        else{
            System.out.print("reject ");
            for (Integer i : reject){
                
                System.out.print(i + " ");
                //System.out.print(i + " ");
            }
        }

        

        
            
    
    }
}


