import java.io.File;
import java.io.FileNotFoundException;
import java.util.*;

public class main {
    public static void main(String[] args) throws FileNotFoundException {
        //to store start stage
        int start = 0;
        String prospect = "";
        Stack<String> currstack = new Stack<>();
        
        //setup initialize all the necessary data strucuts//
        //stack for PDA logic
        //simulation order
        Stack<Integer> stack = new Stack<>();

        //for list of transitions
        //look up transitions.get(curr state) to reduce runtime
        HashMap <Integer,ArrayList <transition>> transitions = new HashMap<>();

        //ensure each config is processed once
        //preventing infinity loops
        HashSet <configuration> visited = new HashSet<>();

        //keep track of configs generated by simulation
        ArrayList<configuration> queue = new ArrayList<>();

        //set of accepting states
        //if not in this set, reject
        HashSet <Integer> acceptstates = new HashSet<>();

        //keep track of generated configurations by simulate
        ArrayList <transition> info = new ArrayList<>();

        //integer arrays to store what stages we accept/reject at
        ArrayList <Integer> accept = new ArrayList<>();
        ArrayList <Integer> reject = new ArrayList<>();        

        //1. put all user input into Arraylist transitions
        Scanner scanner = new Scanner(new File(args[0]));
        prospect = args[1];
        //int counter = 1;
        
        while (scanner.hasNextLine()) {
            

            String line = scanner.nextLine();
            String[] input = line.split("\\s+");

            if (input[0].equals("state")) {

                int id = Integer.parseInt(input[1]);

                if (input.length > 2) {
                    if (input[2].equals("start")) {
                        start = Integer.parseInt(input[1]);
                        
                    }
                    if (input[2].equals("accept")) {
                        acceptstates.add(Integer.parseInt(input[1]));
                    }
                }

                //input.add(new State(id, isStart, isAccept));
            }

            else if (input[0].equals("transition")) {

                //debug purposes 
                /*
                System.out.println("Transition " + counter );
                counter++;
                */

                int from = Integer.parseInt(input[1]);
                String read = input[2];
                String pop = input[3];
                int to = Integer.parseInt(input[4]);
                String push = input[5];

                transition t = new transition(from, read, pop, to, push);

                //creates an empty arraylist for the state
                if (!transitions.containsKey(from)) {
                    transitions.put(from, new ArrayList<>());
                }

                // Add transition to the state list
                transitions.get(from).add(t);
            }
        }

        scanner.close();

        // Test to make sure program is storing data properly
        /* 
        System.out.println("Accept States");
        for (int i : acceptstates) {
            System.out.println(i + " ");
        }

        System.out.println("\n Transition States");
        for (Map.Entry<Integer, ArrayList<transition>> entry : transitions.entrySet()) {

        int state = entry.getKey();
        ArrayList<transition> list = entry.getValue();

        System.out.println("From state: " + state);

            for (transition t : list) {
                System.out.println("   " + t);
            }
        }
        */

        //2.iterate through arraylist of queue
        //stop when theres no more elements to visit
        String remaining = "";
        
        //based on start node, add subsequent transitions to queue
        for (transition t : transitions.get(start)) {
            //testing correct output
            //System.out.println("   " + t.toState);

            currstack.push("$");
            configuration c = new configuration(t.toState, prospect, currstack);
            queue.add(c);
        }

        //not sure why we used this
        // int currstate = start;
        while(!queue.isEmpty()){
            

        //look at  top config, 
        //if its a possible config
        for (configuration c: queue){

        }
        //update a copy stack n copy currStackString
        //remove top config bc we are currently in it

        //if this is an accept state and the currstack is empty, add it to list of accepted states reached
        //clear queue n break from while loop

        //for each potential transition from our hashmap of transitions
        //generate a new config with pointer to the copy stack you made
        //if it's not been visited already, add it to the queue
        
            
        //ignore rn//

            //for each valid transition:
            //generate a new config
            //      if not visited
            //          add tovisited
            //          add to queue
            /*
            for (transition t : transitions.get(currstate)) {
                configuration c = new configuration(t.toState, prospect, currstack);
                queue.add(c);
            }
            */
            

            //having some type of safeguard for this
            //remove curr config
            queue.remove(0);

        }
    }
}
